import 'package:powersync/powersync.dart';

/// 为现有 Drift 业务表创建一个可推断同步映射的 PowerSync Raw Table。
RawTable _rawTable(String name, List<String> syncedColumns) {
  return RawTable.inferred(
    name: name,
    schema: RawTableSchema(
      syncedColumns: syncedColumns,
      options: const TableOptions(ignoreEmptyUpdates: true),
    ),
    clear: 'DELETE FROM "$name"',
  );
}

/// Omni Butler 第一期客户端同步结构。
final Schema omniSyncSchema = Schema(
  const <Table>[
    Table.localOnly('device_sync_metadata', <Column>[Column.text('value')]),
  ],
  rawTables: <RawTable>[
    _rawTable('todo_items', <String>[
      'title',
      'description',
      'scheduled_date',
      'due_at',
      'priority_quadrant',
      'is_completed',
      'completed_at',
      'reminder_at',
      'repeat_rule',
      'repeat_series_id',
      'sort_order',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('quotes', <String>[
      'content',
      'source',
      'is_enabled',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('daily_quote_selections', <String>[
      'day_key',
      'quote_id',
      'is_manual',
      'created_at',
      'updated_at',
    ]),
    _rawTable('taxonomy_entries', <String>[
      'module',
      'kind',
      'name',
      'normalized_name',
      'color_value',
      'icon_code_point',
      'sort_order',
      'is_enabled',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('record_taxonomy_links', <String>[
      'module',
      'record_id',
      'taxonomy_id',
      'created_at',
      'deleted_at',
    ]),
    _rawTable('events', <String>[
      'name',
      'category',
      'description',
      'interval_value',
      'interval_unit',
      'last_completed_at',
      'reminder_enabled',
      'reminder_days_before',
      'reminder_time_minutes',
      'is_archived',
      'archived_at',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('event_completions', <String>[
      'event_id',
      'completed_at',
      'notes',
      'source',
      'is_revoked',
      'created_at',
      'deleted_at',
    ]),
    _rawTable('inventory_items', <String>[
      'name',
      'category',
      'quantity',
      'purchase_price_cents',
      'purchase_date',
      'purchase_url',
      'purchase_platform',
      'location',
      'status',
      'warranty_expiration',
      'tags',
      'parent_item_id',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('time_entries', <String>[
      'entry_date',
      'start_minute',
      'end_minute',
      'started_at',
      'ended_at',
      'activity',
      'category',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('memberships', <String>[
      'name',
      'provider',
      'category',
      'description',
      'website_url',
      'purchase_platform',
      'payment_method',
      'price_cents',
      'billing_cycle',
      'base_status',
      'purchase_date',
      'expiration_date',
      'is_permanent',
      'auto_renew',
      'renewal_date',
      'is_favorite',
      'needs_renewal',
      'expiration_reminder_enabled',
      'expiration_reminder_days',
      'renewal_reminder_enabled',
      'renewal_reminder_days',
      'reminder_time_minutes',
      'cancel_guide',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ]),
    _rawTable('membership_payments', <String>[
      'membership_id',
      'amount_cents',
      'billing_cycle',
      'paid_at',
      'valid_from',
      'valid_until',
      'notes',
      'created_at',
      'deleted_at',
    ]),
  ],
);
